os: linux
dist: focal
group: edge
arch: arm64-graviton2
compiler: clang
script:
  - clang --version
language: python

python:
  - 3.8

install:
  - buildozer -v android debug
  - dpl releases --token $GITHUB_TOKEN --file "bin/mobileapp002-1.1-armeabi-v7a-debug.apk" --tag_name "v.1.1"

  
  
