os: linux
dist: focal
language: python

python:
  - 3.8

install:
  - sudo apt -y install python3-distutils
  - sudo apt -y install python3-pip
  - sudo apt install -y git
  - git clone https://github.com/kivy/buildozer.git
  - python3 -m site
  - ls -l
  - cd buildozer
  - ls -l
  - python3 setup.py install
  - ls -l
  - cd ..
  - ls -l

  - dpl releases --token $GITHUB_TOKEN --file "bin/mobileapp002-0.1-arm64-v8a-debug.apk" --tag_name "v.0.1"

